In [1]:
import pandas as pd
import numpy as np

In [ ]:
filename = 'last_max_window_10000_ochlv.hdf'
pre_df = pd.read_hdf(filename, key='my_data')
pre_df.tail()

,timestamp,open,high,low,close,volume,quote_asset_volume,number_of_trades,taker_buy_base_vol,taker_buy_quote_vol
51445,2025-08-20 07:27:00,113787.82000000,113787.83000000,113777.09000000,113777.09000000,5.65428000,643383.81278120,607,2.39138000,272108.95417460
51446,2025-08-20 07:28:00,113777.10000000,113777.10000000,113736.87000000,113736.87000000,8.25936000,939618.42806220,1633,3.93420000,447568.00574000
51447,2025-08-20 07:29:00,113736.87000000,113736.88000000,113720.86000000,113720.87000000,3.83833000,436509.03110470,636,2.12988000,242212.39140210
51448,2025-08-20 07:30:00,113720.87000000,113720.87000000,113642.86000000,113647.99000000,29.60372000,3365973.77178790,2750,3.48666000,396316.24181400
51449,2025-08-20 07:31:00,113648.00000000,113658.62000000,113618.17000000,113640.00000000,9.60248000,1091202.46140490,2376,5.95792000,677029.84710500

In [ ]:
pre_df.shape

(10000, 10)

In [8]:
start_time = pre_df.iloc[-1]['timestamp']
print(start_time)

2025-08-20 07:31:00

In [10]:
df = pre_df.copy()

In [11]:
columns_to_convert = ['open', 'high', 'low', 'close', 'volume', 'quote_asset_volume', 'taker_buy_base_vol', 'taker_buy_quote_vol']
df[columns_to_convert] = df[columns_to_convert].astype(np.float64)
df['vwap'] = df['quote_asset_volume']/df['volume']
df['returns'] = df['close'].pct_change().fillna(0)
df[['vwap','returns']] = df[['vwap','returns']].astype(np.float64)

In [18]:
import Alpha102 as alpha102
#import Alpha101.Alpha_momentum as alpha_m
df = alpha102.get_ts_alpha(df)
df.tail()

generating alpha007_240generating alpha009_60

generating alpha009_240
generating alpha006_240
generating alpha007_60
generating alpha006_60
generating alpha010_60
generating alpha010_240
generating alpha012_60
generating alpha012_240
generating alpha013_30
generating alpha013_40
generating alpha013_60
generating alpha014_30
generating alpha014_40
generating alpha014_60
generating alpha021_60
generating alpha021_240
generating alpha023_60
generating alpha023_240
generating alpha024_60
generating alpha024_240
generating alpha026_60
generating alpha026_240
generating alpha028_60
generating alpha028_240
generating alpha035_60
generating alpha035_240
generating alpha041
generating alpha043_60
generating alpha043_240
generating alpha046_60
generating alpha046_240
generating alpha049_60
generating alpha049_240
generating alpha051_60
generating alpha051_240
generating alpha053_60
generating alpha053_240
generating alpha054
generating alpha084_60
generating alpha084_240
generating alpha101
generating alpha102_60
generating alpha102_240
generating alpha103_60
generating alpha103_240
generating alpha104
generating alpha104
generating alpha105_60
generating alpha105_240
generating alpha106
generating alpha107_60
generating alpha107_240
generating alpha108_60
generating alpha108_240
generating alpha109_60
generating alpha109_240
generating alpha110_60
generating alpha110_240
generating alpha111_60
generating alpha111_240
generating alpha112_20
generating alpha112_60
generating alpha112_240
generating alpha113_60
generating alpha113_240
generating alpha115_60
generating alpha115_240
generating alpha116_60
generating alpha116_240
generating alpha117_60
generating alpha117_240
generating alpha118_60
generating alpha118_240
generating alpha119
generating alpha120_60
generating alpha120_240
generating alpha121
generating alpha122_60
generating alpha122_240
generating alpha123_60
generating alpha123_240
generating alpha124
generating alpha125_60
generating alpha125_240
generating alpha126_60
generating alpha126_240
generating alpha127_60
generating alpha127_240
generating alpha128_60
generating alpha128_240
generating alpha129
60
0.00556
generating alpha129
240
0.00333
generating alpha130_60
generating alpha130_240
generating alpha131

/usr/local/python/3.12.1/lib/python3.12/site-packages/pywt/_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(

generating alpha131
generating alpha131

/usr/local/python/3.12.1/lib/python3.12/site-packages/pywt/_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(

generating alpha131
alpha006_60_new: <class 'pandas.core.series.Series'>
alpha006_240_new: <class 'pandas.core.series.Series'>
alpha007_60_new: <class 'pandas.core.series.Series'>
alpha007_240_new: <class 'pandas.core.series.Series'>
alpha009_60_new: <class 'pandas.core.series.Series'>
alpha009_240_new: <class 'pandas.core.series.Series'>
alpha010_60_new: <class 'pandas.core.series.Series'>
alpha010_240_new: <class 'pandas.core.series.Series'>
alpha012_60_new: <class 'pandas.core.series.Series'>
alpha012_240_new: <class 'pandas.core.series.Series'>
alpha013_30_new: <class 'pandas.core.series.Series'>
alpha013_40_new: <class 'pandas.core.series.Series'>
alpha013_60_new: <class 'pandas.core.series.Series'>
alpha014_30_new: <class 'pandas.core.series.Series'>
alpha014_40_new: <class 'pandas.core.series.Series'>
alpha014_60_new: <class 'pandas.core.series.Series'>
alpha021_60_new: <class 'pandas.core.series.Series'>
alpha021_240_new: <class 'pandas.core.series.Series'>
alpha023_60_new: <class 'pandas.core.series.Series'>
alpha023_240_new: <class 'pandas.core.series.Series'>
alpha024_60_new: <class 'pandas.core.series.Series'>
alpha024_240_new: <class 'pandas.core.series.Series'>
alpha026_60_new: <class 'pandas.core.series.Series'>
alpha026_240_new: <class 'pandas.core.series.Series'>
alpha028_60_new: <class 'pandas.core.series.Series'>
alpha028_240_new: <class 'pandas.core.series.Series'>
alpha035_60_new: <class 'pandas.core.series.Series'>
alpha035_240_new: <class 'pandas.core.series.Series'>
alpha041_new: <class 'pandas.core.series.Series'>
alpha043_60_new: <class 'pandas.core.series.Series'>
alpha043_240_new: <class 'pandas.core.series.Series'>
alpha046_60_new: <class 'pandas.core.series.Series'>
alpha046_240_new: <class 'pandas.core.series.Series'>
alpha049_60_new: <class 'pandas.core.series.Series'>
alpha049_240_new: <class 'pandas.core.series.Series'>
alpha051_60_new: <class 'pandas.core.series.Series'>
alpha051_240_new: <class 'pandas.core.series.Series'>
alpha053_60_new: <class 'pandas.core.series.Series'>
alpha053_240_new: <class 'pandas.core.series.Series'>
alpha054_new: <class 'pandas.core.series.Series'>
alpha084_60_new: <class 'pandas.core.series.Series'>
alpha084_240_new: <class 'pandas.core.series.Series'>
alpha101_new: <class 'pandas.core.series.Series'>
alpha102_60_new: <class 'pandas.core.series.Series'>
alpha102_240_new: <class 'pandas.core.series.Series'>
alpha103_60_new: <class 'pandas.core.series.Series'>
alpha103_240_new: <class 'pandas.core.series.Series'>
alpha104_60_240_new: <class 'pandas.core.series.Series'>
alpha104_240_720_new: <class 'pandas.core.series.Series'>
alpha105_60_new: <class 'pandas.core.series.Series'>
alpha105_240_new: <class 'pandas.core.series.Series'>
alpha106_new: <class 'pandas.core.series.Series'>
alpha107_60_new: <class 'pandas.core.series.Series'>
alpha107_240_new: <class 'pandas.core.series.Series'>
alpha108_60_new: <class 'pandas.core.series.Series'>
alpha108_240_new: <class 'pandas.core.series.Series'>
alpha109_60_new: <class 'pandas.core.series.Series'>
alpha109_240_new: <class 'pandas.core.series.Series'>
alpha110_60_new: <class 'pandas.core.series.Series'>
alpha110_240_new: <class 'pandas.core.series.Series'>
alpha111_60_new: <class 'pandas.core.series.Series'>
alpha111_240_new: <class 'pandas.core.series.Series'>
alpha112_20_new: <class 'pandas.core.series.Series'>
alpha112_60_new: <class 'pandas.core.series.Series'>
alpha112_240_new: <class 'pandas.core.series.Series'>
alpha113_60_new: <class 'pandas.core.series.Series'>
alpha113_240_new: <class 'pandas.core.series.Series'>
alpha115_60_new: <class 'pandas.core.series.Series'>
alpha115_240_new: <class 'pandas.core.series.Series'>
alpha116_60_new: <class 'pandas.core.series.Series'>
alpha116_240_new: <class 'pandas.core.series.Series'>
alpha117_60_new: <class 'pandas.core.series.Series'>
alpha117_240_new: <class 'pandas.core.series.Series'>
alpha118_60_new: <class 'pandas.core.series.Series'>
alpha118_240_new: <class 'pandas.core.series.Series'>
alpha119_new: <class 'pandas.core.series.Series'>
alpha120_60_new: <class 'pandas.core.series.Series'>
alpha120_240_new: <class 'pandas.core.series.Series'>
alpha121_new: <class 'pandas.core.series.Series'>
alpha122_60_new: <class 'pandas.core.series.Series'>
alpha122_240_new: <class 'pandas.core.series.Series'>
alpha123_60_new: <class 'pandas.core.series.Series'>
alpha123_240_new: <class 'pandas.core.series.Series'>
alpha124_new: <class 'pandas.core.series.Series'>
alpha125_60_new: <class 'pandas.core.series.Series'>
alpha125_240_new: <class 'pandas.core.series.Series'>
alpha126_60_new: <class 'pandas.core.series.Series'>
alpha126_240_new: <class 'pandas.core.series.Series'>
alpha127_60_new: <class 'pandas.core.series.Series'>
alpha127_240_new: <class 'pandas.core.series.Series'>
alpha128_60_new: <class 'pandas.core.series.Series'>
alpha128_240_new: <class 'pandas.core.series.Series'>
alpha129_60_0.00556_new: <class 'pandas.core.series.Series'>
alpha129_240_0.00333_new: <class 'pandas.core.series.Series'>
alpha130_60_new: <class 'pandas.core.series.Series'>
alpha130_240_new: <class 'pandas.core.series.Series'>
alpha131_60_1_new: <class 'pandas.core.series.Series'>
alpha131_240_1_new: <class 'pandas.core.series.Series'>
alpha131_60_2_new: <class 'pandas.core.series.Series'>
alpha131_240_2_new: <class 'pandas.core.series.Series'>
运行时间: 86.0567 秒

,timestamp,open,high,low,close,volume,quote_asset_volume,number_of_trades,taker_buy_base_vol,taker_buy_quote_vol,...,alpha128_60_new,alpha128_240_new,alpha129_60_0.00556_new,alpha129_240_0.00333_new,alpha130_60_new,alpha130_240_new,alpha131_60_1_new,alpha131_240_1_new,alpha131_60_2_new,alpha131_240_2_new
51445,2025-08-20 07:27:00,113787.82,113787.83,113777.09,113777.09,5.65428,6.433838e+05,607,2.39138,272108.954175,...,0.629449,0.896992,0.001243,0.002769,0.003867,0.006329,-3.238358,11.394629,5.943841,7.107656
51446,2025-08-20 07:28:00,113777.10,113777.10,113736.87,113736.87,8.25936,9.396184e+05,1633,3.93420,447568.005740,...,0.887169,0.895877,0.001124,0.002727,0.003490,0.006230,-6.805997,15.462518,-2.318295,12.902901
51447,2025-08-20 07:29:00,113736.87,113736.88,113720.86,113720.87,3.83833,4.365090e+05,636,2.12988,242212.391402,...,0.716567,0.909430,0.001106,0.002701,0.003443,0.006166,-11.337823,17.299916,-7.689125,10.933648
51448,2025-08-20 07:30:00,113720.87,113720.87,113642.86,113647.99,29.60372,3.365974e+06,2750,3.48666,396316.241814,...,0.725132,0.935736,0.001138,0.002681,0.003536,0.006118,-15.341075,17.510535,-6.847527,1.150470
51449,2025-08-20 07:31:00,113648.00,113658.62,113618.17,113640.00,9.60248,1.091202e+06,2376,5.95792,677029.847105,...,0.720902,0.891759,0.001150,0.002666,0.003573,0.006085,-17.439122,14.920751,-3.571391,-10.763961

In [19]:
df.shape

(10000, 112)

In [22]:
import json
from utils.helper import rolling_z_score, z_score_from_json

df, result_list = rolling_z_score(df,window=50000,exclude_cols=['timestamp','treatment', 'amplitude', 'custom_std'])
#new_row = z_score_from_json(df.tail(1440), 'config_train_rolling_50000.json')
df.tail(1)
# new_row = df[df['timestamp'] == pd.Timestamp('2025-07-27 06:50:00')]
# new_row = z_score_from_json(new_row, 'config.json')
# new_row.tail(1)

,timestamp,open,high,low,close,volume,quote_asset_volume,number_of_trades,taker_buy_base_vol,taker_buy_quote_vol,...,alpha128_60_new,alpha128_240_new,alpha129_60_0.00556_new,alpha129_240_0.00333_new,alpha130_60_new,alpha130_240_new,alpha131_60_1_new,alpha131_240_1_new,alpha131_60_2_new,alpha131_240_2_new
51449,2025-08-20 07:31:00,-0.699881,-0.703744,-0.702872,-0.702557,0.047776,0.039523,0.379528,0.262357,0.24804,...,-1.075819,0.192169,-0.659672,-0.681308,-0.684213,-0.707434,-1.158569,0.496227,-0.229888,-1.175492

In [23]:
print(df.shape)

(10000, 112)

In [24]:
new_row = df.tail(1440)
features = new_row[[col for col in new_row.columns if col not in ['timestamp', 'close_time', 'treatment', 'amplitude', 'custom_std']]].values.astype(np.float32)
features.shape

(1440, 111)

In [25]:
import json

# 假设 features 是 shape (1440, 111) 的 numpy 数组
one_sample = features[0].tolist()  # 取第一行并转为 list

with open("input.json", "w") as f:
    json.dump([one_sample], f)  # 注意外面要加一层[]，表示 batch 维度

In [26]:
# get 10 sample
import json

ten_sample = features[:10].tolist()  # 取前10行并转为 list
with open("input_10.json", "w") as f:
    json.dump(ten_sample, f)  # 注意外面要加一层[]，表示 batch 维度